### ISSUE TITLE
【新功能】中西文字体、「自动清除过期作业」开关

### ISSUE THREAD

**Issue by Jursin** [Sticky-attention/Sticky-attention#11]
**类型**
`设置`

**描述**
1.统一分别设置中西文字体（想将所有西文字体设为`Times New Roman`）
2.增加`自动清除过期作业`开关（其实不想打开这个功能，有时收作业的时间不确定，到那天后又会被自动清除）

**Comment by jizilin6732** [comment]
- [ ] 目前已更换MiSans字体 后续可能支持用户自行更换
- [ ] 自动作业开关 将在近期更新(可能更不了)

**Comment by jizilin6732** [comment]
已完成✅
