### ISSUE TITLE
【Bug】全屏窗口后无法取消全屏

### ISSUE THREAD

**Issue by Jursin** [Sticky-attention/Sticky-attention#23]
**描述**
在未固定状态将窗口全屏后无法取消

**复现**
在未固定状态将窗口拖动到屏幕边缘自动全屏，后无法拖动边缘以取消全屏

**预期行为**
修复问题

**设备信息**
- 厂商：联想
- 操作系统：Windows 11
- 版本号：23H2
- 系统类型：x64
- 触控设备：否

**Comment by jizilin6732** [comment]
已完成修复！
