### ISSUE TITLE
【Bug】更新进度显示-1%

### ISSUE THREAD

**Issue by MF-Dust** [Sticky-attention/Sticky-attention#28]
**描述**

在设置界面检查更新时,进度为-1%
**复现**

![{EF67D4F4-9007-41A3-A0D2-358B7EAA559A}](https://github.com/user-attachments/assets/6be93d37-4453-46f3-82f5-cd44b810dc75)

**预期行为**
正常显示更新进度

**设备信息**
- 厂商：
- 操作系统：Windows 11
- 版本号：10.0.26100.1742
- 系统类型：x64
- 触控设备: 否

**Comment by jizilin6732** [comment]
特色（
