### ISSUE TITLE
【Bug】文字属性面板超出屏幕边缘

### ISSUE THREAD

**Issue by Jursin** [Sticky-attention/Sticky-attention#3]
**描述**
文字属性面板超出屏幕边缘

**复现**
将窗口某侧拖到屏幕边缘并固定，在编辑作业时面板会显示在屏幕边缘，只剩下一点，勉强能手动拖回中间

**预期行为**
优化面板显示逻辑

**设备信息**
- 厂商：鸿合
- 操作系统：Windows 11 x64
- 版本：23H2

**Comment by Jursin** [comment]
![2024-09-29_19-37-58.png](https://github.com/user-attachments/assets/9ce0bea9-1d8a-48dd-aaad-863a6a34a060)

就是这样，可以看到屏幕右侧边缘只露出一点点，勉强能拖出来

**Comment by jizilin6732** [comment]
收到 下个版本完成修复

**Comment by jizilin6732** [comment]
已完成修复

**Comment by jizilin6732** [comment]
由于修改其他内容 导致改bug复现 故重新修复

**Comment by jizilin6732** [comment]
修复完毕
