### ISSUE TITLE
【新功能】将重启按钮改为缩小窗口按钮

### ISSUE THREAD

**Issue by belugaQAQ** [Sticky-attention/Sticky-attention#37]
**“老师总是关掉SA...**
_诶停停停，这个和上次不一样_
# 我们不应该一味的阻止老师关掉
我们可以把重启按钮换成缩小窗口按钮
> 这样有两个好处
- 老师不会关闭窗口
- 修复自动缩小无法展开
> 需要修复一个BUG
- 缩小窗口后展开大小改变

**Comment by jizilin6732** [comment]
已完成✅
