### ISSUE TITLE
【Bug】使用过程中有概率界面卡住

### ISSUE THREAD

**Issue by Jursin** [Sticky-attention/Sticky-attention#4]
**描述**
使用过程中有概率界面卡住，在固定后显示类似非固定的状态，但点击界面任意位置无响应，只能强行重启进程

**复现**
- 在固定后，长按主界面边缘并滑动
- 编辑作业时缓慢拖动属性面板
- 从其他界面突然转到作业面板时

**预期行为**
修复该问题

**设备信息**
- 厂商：鸿合
- 操作系统：Windows 11 x64
- 版本：23H2

**Comment by jizilin6732** [comment]
未能成功复现 建议录屏上传

**Comment by Jursin** [comment]
> 未能成功复现 建议录屏上传

明天到班里录屏试试吧

**Comment by jizilin6732** [comment]
猜测:应该是应用对触屏视频不完善 后续可提供日志 我将尽快解决

**Comment by jizilin6732** [comment]
开始重构
