### ISSUE TITLE
【Bug】长按选择文字后浮动小窗口置底

### ISSUE THREAD

**Issue by Misaka2298** [Sticky-attention/Sticky-attention#42]
**描述**
如题。

**复现**
1.布置一条作业。
2.打开编辑模式。
3.长按文字，选择“全选”

**预期行为**
浮动小窗口（更改作业样式的那个）正常置顶。

**实际行为**
浮动小窗口置底（在本软件主界面之下，无法点击）。

**设备信息**
- 厂商：Seewo
- 操作系统：Windows 10 LTSC
- 版本号：21H2
- 系统类型：x64
- 触控设备：是

**Comment by jizilin6732** [comment]
已修复
