### ISSUE TITLE
[Bug]: 无法获取更新？

### ISSUE THREAD

**Issue by PrefacedCorg** [Sticky-attention/Sticky-attention#61]
### 联系方式

QQ：1876568293

### 描述并复现碰到了的问题！

更新界面显示114514 无法正常更新
挂代理等方法都试过
不是网络的问题

### 版本

最新测试版

### 系统版本

win11（64）

### 触屏设备

否

### 你在软件的哪个方面遇到了问题？

其他

### 提问时的智慧

- [X] 我已了解并遵守【提问时的智慧】

**Comment by jizilin6732** [comment]
已修复
